receivers:
  otlp:
    protocol: http
    host: 0.0.0.0
    port: 4317
exporters:
  otlp/tempo:
    endpoint: http://tempo:4317
    insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    username: ""
    password: ""
    tenant_id: ""
    labels:
      job: "otel-collector"
      service: "nextjs-app"
processors:
  batch:
    timeout: 10s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]